CRNT-25444: Added XSD/EMF plugins because we're no longer repackaging these classes (otherwise NoClassDefFoundError is thrown if we don't add these plugins)
git-svn-id: https://svn.csa.sungard.com/repos/ipp2/product/trunk/stardust/ide@67888 8100b5e0-4d52-466c-ae9c-bdeccbdeaf6b